title = "LB"
baseURL = "https://lindsaybrunner.com"
languageCode = "en-us"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
googleAnalytics = ""

[permalinks]
  blog = "/blog/:slug/"
  thoughts = "/thoughts/:year-:month-:day/:slug/"
  recipes = "/recipes/:year-:month-:day/:slug/"

[pagination]
pagerSize = 9
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  description = "Developer advocacy leader, content strategist, and technical writer helping developers build better experiences."
  author = "Lindsay Brunner"

  # Social links
  twitter = "https://twitter.com/cookwithlindsay"
  instagram = "https://www.instagram.com/lindsayb610/"
  github = "https://github.com/LindsayB610"
  linkedin = "https://www.linkedin.com/in/lindsaybrunner/"
  bluesky = "https://bsky.app/profile/cookwithlindsay.bsky.social"

  # Site config
  recent_posts_number = 4
  show_reading_time = true
  default_social_image = "/images/social/default-og.png"

  # SEO
  keywords = "developer advocacy, content strategy, technical writing, developer experience"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[outputs]
  section = ["HTML", "RSS"]

[outputFormats]
  [outputFormats.RSS]
    mediatype = "application/rss+xml"
    baseName = "index"
    isPlainText = true
    notAlternative = true
  [outputFormats.RecipeSearch]
    mediatype = "application/json"
    baseName = "index"
    isPlainText = true
    notAlternative = true

# Disable taxonomies completely - prevent Hugo from generating /categories/ and /tags/ pages
disableKinds = ["taxonomy", "taxonomyTerm"]
