[build]
publish = "public"
command = "npm install && npx hugo --gc --minify"

[context.production.environment]
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"
NODE_VERSION = "20"

[context.split1]
command = "npm install && npx hugo --gc --minify --enableGitInfo"

[context.split1.environment]
HUGO_ENV = "production"
NODE_VERSION = "20"

[context.deploy-preview]
command = "npm install && npx hugo --gc --minify --buildFuture --baseURL $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
NODE_VERSION = "20"

[context.branch-deploy]
command = "npm install && npx hugo --gc --minify --baseURL $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
NODE_VERSION = "20"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"
